Location/Location/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('location/',include('myapp.urls')),
]

Location/myapp/urls.py
from django.urls import path
from myapp import views


app_name = 'myapp'
urlpatterns = [

	path('',views.find,name = 'find'),
	path('add',views.add,name = 'add'),
	path('getplace',views.get,name = 'get'),



]

Location/myapp/models.py
from django.db import models

# Create your models here.

class Location(models.Model):
	key 		= models.CharField(max_length = 20)
	place_name 	= models.CharField(max_length = 50)
	admin_name 	= models.CharField(max_length = 50)
	latitude 	= models.FloatField(max_length = 10)
	longitude 	= models.FloatField(max_length = 10)



	def __str__(self):
		return self.key
	

Location/myapp/views.py
from django.shortcuts import render,redirect
from myapp.models import Location
from geopy.geocoders import Nominatim
from math import *

# Create your views here.
def index(request):
	locations = Location.objects.all()
	return render(request,'index.html',{'locations':locations})


def find(request):

	if request.method == "POST":
		lat1 = request.POST['latitude']
		lon1 = request.POST['longitude']
		rad  = request.POST['radius']
		print(type(lat1),type(lon1))
		# data = Location.objects.get(latitude=lat,longitude=lon)
		# print(data)
		locations = Location.objects.all()
		arr = []
		for location in locations:
			R = 6373.0
			try:
				lat2 = radians(location.latitude)
				lon2 = radians(location.longitude)

				dlon = lon2 - radians(float(lon1))
				print(type(dlon))
				dlat = lat2 - radians(float(lat1))
				print(type(dlat))
				try:
					a = sin(dlat / 2)**2 +cos(radians(float(lat1)))*cos(lat2)*sin(dlon/2)**2
					c = 2 * atan2(sqrt(a), sqrt(1-a))
					distance = R*c
				except Exception as e2:
					print(e2)

				if distance<=int(rad):
					arr.append(str(location.place_name)+
						" is at distance "
						+str(distance)
						+"km "
						+"--> Pincode is "
						+str(location.key))
				else:
					continue
			except Exception as e:
				print(e)
				print(location.key)
		print(arr)


		return render(request,'myapp/find.html',{'data':arr})

	return render(request,'myapp/find.html')


def add(request):
	if request.method == "POST":
		pin 	= "IN/"+str(request.POST['pincode'])
		place 	= request.POST['place'].capitalize()
		admin 	= request.POST['admin'].capitalize()
		lat 	= float(request.POST['latitude'])
		lon 	= float(request.POST['longitude'])

		print(pin)
		print(place)
		print(admin)
		print(lat)
		print(lon)

		location = Location.objects.get_or_create(key=pin,place_name=place,admin_name=admin,latitude=lat,longitude=lon)
		print(location)




	return render(request,'myapp/add.html')

def get(request):

	if request.method == "POST":
		lat = request.POST['latitude']
		lon = request.POST['longitude']
		loc ='"'+str(lat)+","+str(lon)+'"'
		try:
			geolocator = Nominatim(user_agent ='myapp')
			location = geolocator.reverse(loc)
			a = location.address
			a = a.split(',')
			return render(request,'myapp/get_place.html',{'data':a})
		except Exception as e:
			return render(request,'myapp/get_place.html',{'errors':'Invalid Coordinates'})


	return render(request,'myapp/get_place.html')

Location/myapp/templates/myapp/add.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Locations</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<style type="text/css">
				body
				{
					font-family: "Courier",sans-serif;
				}
				h1{
					text-decoration: underline;
				}
		</style>
</head>
<body>
	<main class="container">
	<h1 align="center">Add New Locations Here!</h1>
	<a href="{% url 'index' %}" class="btn btn-outline-warning">Homepage</a>
	<p></p>
	<hr>
	<div class="jumbotron">
		<form method="POST">
			{% csrf_token %}
			Enter Pincode:<br><input type="text" name="pincode" required><p></p>
			Enter PlaceName:<br><input type="text" name="place" required><p></p>
			Enter AdminName:<br><input type="text" name="admin" required><p></p>
			Enter Latitude:<br><input type="text" name="latitude" required><p></p>
			Enter Longitude:<br><input type="text" name="longitude" required><p></p>
			<p></p>
			<input type="submit" name="submit" class="btn btn-primary">
		</form>
	</div>
	<hr>
	</main>
</body>
</html>

Location/myapp/templates/myapp/find.html
<!DOCTYPE html>
<html>
<head>
	<title>Find Locations Around Zip</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<style type="text/css">
				body{
			font-family: "Courier",sans-serif;
		}
				h1{
					text-decoration: underline;
				}
		</style>
</head>
<body>

</body>
<main class="container">
	<h1 align="center">This is Find Locations Page!</h1>
	<a href="{% url 'index' %}" class="btn btn-outline-warning">Homepage</a>
	<p></p>
	<hr>
	
		
		<div class="jumbotron">
			
			<form method="POST">
				{% csrf_token %}
				Latitude :<br> <input type="text" name="latitude" required><p></p>

				Longitude :<br> <input type="text" name="longitude" required><p></p>

				Radius :<br><input type="number" name="radius" required><p></p>

				<input type="submit" name="submit" class="btn btn-primary">



			</form>

		</div>
		<hr>
				<div class="data">
				{% if data %}
				<h1>All matching patterns!</h1>
				<ul>
					{% for i in data %}
					<li>{{ i }}
					</li>
					<hr>
					{% endfor %}
				</ul>
			{% endif %}
			</div>
	</main>
</html>

Location/myapp/templates/myapp/get_place.html
<!DOCTYPE html>
<html>
<head>
	<title>Get Place</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<style type="text/css">
					h1{
			text-decoration: underline;
		}
				body{
			font-family: "Courier",sans-serif;
		}
		ul{
			font-weight: bold;
			font-size: 1.2em;
			box-shadow: 2px 2px 2px grey;
			width:400px;
		}
		</style>
</head>
<body>
	<main class="container">
	<h1 align="center">Get Place By Longitude and Latitude</h1>
	<a href="{% url 'index' %}" class="btn btn-outline-warning">Homepage</a>
	<p></p>
	<hr>
	<div class="jumbotron">
		<form method="POST">
			
				{% csrf_token %}
				Latitude :<br> <input type="text" name="latitude" required><p></p>

				Longitude :<br> <input type="text" name="longitude" required><p></p>
				<input type="submit" name="submit" class="btn btn-primary">			

		</form>
	</div>
	<hr>
	<div class="data">
			{% if data %}
				<ul>
					<h3>Place:</h3>
					{% for i in data %}
						{{ i }}<br>
					{% endfor %}
				</ul>

			{% endif %}
			{% if errors %}
				<h2>Error:- {{ errors }}</h2>
			{% endif%}
	</div>
	</main>
</body>
</html>

Location/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>All Locations</title>
	<style type="text/css">
		body{
			font-family: "Courier",sans-serif;
		}
		h1{
			text-decoration: underline;
		}
		a{
			margin-left: 20px;
			text-decoration: none;
		}
		li{
			width: 400px;
			border:1px solid black;
			box-shadow: 2px 2px 2px grey;
			padding-left: 5px;
		}

	</style>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>
	<main class="container">
	<h1 align="center"> All Locations In Database </h1>
	<a class="btn btn-outline-primary first" href="{% url 'myapp:add' %}">Add New Location</a>
	<a class="btn btn-outline-primary second" href="{% url 'myapp:find' %}">Find Locations In A Range Of Km</a>
	<a class="btn btn-outline-primary first" href="{% url 'myapp:get' %}">Find Place From Lat & Lan</a>
	<hr>
	<ul>
	{% for location in locations %}
		<li> SNo. : {{ location.pk }}<br>
			 Pincode : {{ location.key }}<br>
			 PlaceName : {{ location.place_name }}<br>
			 AdminName : {{ location.admin_name }}<br>
			 Latitude : {{ location.latitude }}<br>
			 Longitude : {{ location.longitude }} </li>
		<p></p>
	{% endfor %}
	</ul>
</main>
</body>
</html>